// Fachbegriffe
export const FACHBEGRIFFE = [
  // === NIERE & INKONTINENZ ===
  {term:'Nephron',def:'Funktionelle Grundeinheit der Niere — besteht aus Nierenkörperchen (Glomerulus + Bowman-Kapsel) und Nierenkanälchen (Tubuli). 1–1,5 Mio. pro Niere'},
  {term:'Glomerulus',def:'Kapillarknäuel im Nierenkörperchen — filtert den Primärharn (~180 L/Tag) aus dem Blut (Ultrafiltration)'},
  {term:'Primärharn',def:'Ultrafiltrat des Blutes im Glomerulus (~180 L/Tag). Enthält Wasser, Elektrolyte, Glukose, Aminosäuren — noch kein Endharn'},
  {term:'Sekundärharn',def:'Endharn nach Rückresorption im Tubulus (~1,5–2 L/Tag). 99% des Primärharns werden rückresorbiert'},
  {term:'Henle-Schleife',def:'Teil des Nierenkanälchens im Nierenmark — wichtig für Wasserrückresorption und Harnkonzentrierung'},
  {term:'Erythropoetin',def:'Hormon der Nieren — stimuliert die Bildung roter Blutkörperchen im Knochenmark. Mangel bei Nierenversagen → renale Anämie'},
  {term:'Renin',def:'Hormon der Nieren bei Blutdruckabfall → aktiviert Angiotensin-Kaskade → Blutdrucksteigerung (Renin-Angiotensin-System)'},
  {term:'M. detrusor vesicae',def:'Blasenwandmuskel — Kontraktion durch Parasympathikus (S2–S4) → Miktion. Entspannung durch Sympathikus → Blasenfüllung'},
  {term:'Miktionsreflex',def:'Reflex zur Blasenentleerung: Dehnungsrezeptoren → Rückenmark → Parasympathikus → Detrusor kontrahiert, Sphinkter erschlafft'},
  {term:'Miktionszentrum',def:'Übergeordnetes Zentrum im Gehirn (Großhirn + Hirnstamm): steuert ab 3. Lebensjahr bewusst Kontinenz und Miktion'},
  {term:'Kontinenz',def:'Fähigkeit zur willkürlichen Blasenentleerung zu passender Zeit und am passenden Ort — Gegenteil von Inkontinenz'},
  {term:'Harninkontinenz',def:'Unfreiwilliger Harnverlust jeglichen Ausmaßes (ICS). Kein Krankheitsbild, sondern ein Symptom — 2x/Monat oder öfter (Norton 1999)'},
  {term:'Belastungsinkontinenz',def:'Harnabgang bei körperlicher Belastung (Husten/Niesen = Grad I, Heben = Grad II, Liegen = Grad III) ohne Harndrang'},
  {term:'Dranginkontinenz',def:'Überaktivität des Detrusors → unkontrollierte Blasenentleerung trotz intaktem Schließmechanismus. Ursachen: neurologisch, Infektion, psychisch'},
  {term:'Reflexinkontinenz',def:'Neurogene Inkontinenz durch Nervenstörung (Rückenmarkschädigung, MS) — kein willentlicher Harnverlust möglich, Blase nicht wahrnehmbar'},
  {term:'Funktionelle Inkontinenz',def:'Urogenitaltrakt intakt, aber Demenz/Immobilität/Depression verhindern rechtzeitigen Toilettengang'},
  {term:'Harnretention',def:'Unvollständige Blasenentleerung mit Restharnbildung. Chronisch: Blasenüberdehnung, Abflussbehinderung (Prostata, Blasenstein)'},
  {term:'Miktionsprotokoll',def:'Dokumentation von Trinkmenge, Miktionsfrequenz, -menge und Inkontinenzepisoden — wichtigstes Assessmentinstrument'},
  {term:'Kontinenzprofil',def:'Pflegediagnostisches Ziel im Expertenstandard: beschreibt angestrebte Kontinenzsituation des Pflegebedürftigen'},
  {term:'Beckenbodentraining',def:'Gezielte Kräftigung der Beckenbodenmuskulatur → Unterstützung des äußeren Schließmuskels → Indikation: Belastungsinkontinenz'},
  {term:'Dekubitus',def:'Lokal begrenzte Schädigung der Haut/des Gewebes über knöchernen Vorsprüngen infolge von Druck oder Druck + Scherkräften (NPUAP/EPUAP)'},
  {term:'Ischämie',def:'Mangeldurchblutung eines Gewebes durch Druckkompression der Blutgefäße → Hypoxie → Zelluntergang'},
  {term:'Scherkräfte',def:'Entgegengesetzt zueinander wirkende Kräfte innerhalb eines Gewebes — führen zu Gefäßabknickung und Gewebsdeformation'},
  {term:'EPUAP',def:'European Pressure Ulcer Advisory Panel — erstellt die internationale Klassifikation von Dekubitus in 4 Kategorien'},
  {term:'NPUAP',def:'National Pressure Ulcer Advisory Panel — US-amerikanische Organisation, gemeinsam mit EPUAP Urheber der Dekubitusklassifikation'},
  {term:'Prädilektionsstellen',def:'Bevorzugte Entstehungsorte von Dekubitus: Kreuzbein (#1), Fersen, Hüfte (Trochanter), Knöchel, Hinterkopf'},
  {term:'IAD',def:'Inkontinenz assoziierte Dermatitis — feuchtigkeitsbedingte Hautschädigung durch Urin/Stuhl, KEIN Dekubitus'},
  {term:'Intertrigo (ITD)',def:'Intertriginöse Dermatitis durch Schwitzen und Reibung in Hautfalten (Rima ani, inguinal)'},
  {term:'MASD',def:'Moisture-associated skin damage — Oberbegriff für feuchtigkeitsbedingte Hautschäden (IAD, ITD, Mazeration)'},
  {term:'Mazeration',def:'Aufweichung der Haut durch länger anhaltende Feuchtigkeit — erhöht Dekubitusrisiko erheblich'},
  {term:'Nekrose',def:'Gewebetod durch anhaltende Unterversorgung (Ischämie) oder direkte mechanische Schädigung'},
  {term:'Unterminierung',def:'Taschenartige Gewebezerstörung unter intakter Haut am Wundrand — Zeichen für tiefe Dekubitus'},
  {term:'NPWT',def:'Negative Pressure Wound Therapy (Unterdrucktherapie) — bei tiefen Dekubitusulzera, fördert Granulation'},
  {term:'Osteomyelitis',def:'Knochenmarkentzündung — schwere Komplikation bei Kategorie IV Dekubitus mit freiliegendem Knochen'},
  {term:'Expertenstandard',def:'Wissenschaftlich begründeter Standard des DNQP — Dekubitusprophylaxe 2017: 6 Handlungsebenen, verbindlich für Pflegepersonal'},
  {term:'DNQP',def:'Deutsches Netzwerk für Qualitätsentwicklung in der Pflege — erstellt evidenzbasierte Expertenstandards'},
  {term:'Braden-Skala',def:'Dekubitusrisikoskala mit 6 Faktoren (Aktivität, Mobilität, Ernährung, Feuchtigkeit, Reibung, Sensibilität). Niedrigerer Wert = höheres Risiko'},
  {term:'Hyperämisierende Salben',def:'ABC-Salbe, Finalgon — ZUR DEKUBITUSPROPHYLAXE OBSOLET! Verursachen Gewebsschäden statt zu schützen'},
  {term:'Bradykardie',def:'Herzfrequenz unter 60 Schläge pro Minute'},
  {term:'Hypertonie',def:'Bluthochdruck – systolischer Wert über 140 mmHg'},
  {term:'Hypotonie',def:'Niedriger Blutdruck – systolischer Wert unter 90 mmHg'},
  {term:'Dyspnoe',def:'Atemnot / erschwertes Atmen'},
  {term:'Apnoe',def:'Atemstillstand'},
  {term:'Tachypnoe',def:'Beschleunigte Atmung (über 20 Atemzüge/min)'},
  {term:'Bradypnoe',def:'Verlangsamte Atmung (unter 12 Atemzüge/min)'},
  {term:'Zyanose',def:'Bläuliche Verfärbung der Haut durch Sauerstoffmangel'},
  {term:'Ödeme',def:'Ansammlung von Flüssigkeit im Gewebe'},
  {term:'Dekubitus',def:'Druckgeschwür durch anhaltenden Druck auf die Haut'},
  {term:'Dysphagie',def:'Schluckstörung / erschwertes Schlucken'},
  {term:'Exsikkose',def:'Austrocknung des Körpers (Dehydration)'},
  {term:'Hypoglykämie',def:'Unterzuckerung – Blutzucker unter 70 mg/dl'},
  {term:'Hyperglykämie',def:'Überzuckerung – erhöhter Blutzucker'},
  {term:'Anamnese',def:'Erhebung der Krankengeschichte eines Patienten'},
  {term:'Diagnose',def:'Feststellung einer Krankheit anhand von Symptomen'},
  {term:'Prognose',def:'Voraussage über den Krankheitsverlauf'},
  {term:'Prophylaxe',def:'Vorbeugung / Maßnahmen zur Krankheitsverhütung'},
  {term:'Rehabilitation',def:'Wiederherstellung der körperlichen/geistigen Funktionen'},
  {term:'MRSA',def:'Methicillin-resistenter Staphylococcus aureus – multiresistenter Erreger'},
  {term:'Nosokomial',def:'Im Krankenhaus entstanden / krankenhauserworbene Infektion'},
  {term:'Sublingual',def:'Unter die Zunge (Applikationsweg für Medikamente)'},
  {term:'Intravenös (i.v.)',def:'In die Vene hinein – direkter Weg ins Blut'},
  {term:'Subkutan (s.c.)',def:'Unter die Haut – ins Fettgewebe (z.B. Insulin)'},
  // Diabetes Mellitus Fachbegriffe
  {term:'Hypoglykämie',def:'Unterzuckerung – Blutzucker unter 70 mg/dl → Zittern, Schwitzen, Verwirrtheit'},
  {term:'Hyperglykämie',def:'Überzuckerung – erhöhter Blutzucker über 126 mg/dl nüchtern'},
  {term:'Glukosurie',def:'Ausscheidung von Zucker im Urin – ab BZ über 180 mg/dl (Nierenschwelle)'},
  {term:'Polydipsie',def:'Vermehrter Durst – Folge von Glukosurie und Wasserverlust bei Diabetes'},
  {term:'Polyurie',def:'Vermehrtes Wasserlassen – häufiges Symptom bei Diabetes mellitus'},
  {term:'HbA1c',def:'Langzeitblutzucker der letzten 3–4 Monate in % – Normwert 4–6%'},
  {term:'BZTP',def:'Blutzuckertagesprofil – BZ nüchtern, vor und 2h nach den Mahlzeiten'},
  {term:'Insulin',def:'Hormon der B-Zellen – senkt den Blutzucker (B = Bremse)'},
  {term:'Glukagon',def:'Hormon der A-Zellen – erhöht den Blutzucker (A = Anstieg)'},
  {term:'Ketoazidose',def:'Lebensbedrohliche Übersäuerung bei Typ-1-Diabetes durch Ketonkörper'},
  {term:'Makroangiopathie',def:'Schädigung großer Blutgefäße bei Diabetes → Herzinfarkt, Schlaganfall, pAVK'},
  {term:'Mikroangiopathie',def:'Schädigung kleiner Gefäße (Kapillaren) → Retinopathie, Nephropathie'},
  {term:'Polyneuropathie',def:'Nervenschäden durch Diabetes → Kribbeln, Taubheit, Muskelschwäche'},
  {term:'Mal perforans',def:'Schmerzloses Ulkus an der Fußsohle beim neuropathischen diabetischen Fuß'},
  {term:'Metformin',def:'Erstlinien-Medikament bei Typ-2-Diabetes (Biguanid) – kein Insulin!'},
  {term:'Insulinresistenz',def:'Zellen reagieren schlechter auf Insulin → Pankreas erschöpft sich → Typ-2-Diabetes'},
  // Haut Fachbegriffe
  {term:'Cutis',def:'Lateinisch für Haut = Epidermis + Dermis (größtes und nervenreichstes Organ)'},
  {term:'Epidermis',def:'Oberhaut — keine Gefäße, erneuert sich alle 30 Tage, sitzt auf der Basalmembran'},
  {term:'Dermis',def:'Lederhaut — enthält Blutgefäße, Nerven, Haarfollikel, Talg- und Schweißdrüsen'},
  {term:'Subcutis',def:'Unterhaut und Fettgewebe — Wärmedämmung, Energiespeicher, Stoßdämpfer'},
  {term:'Melanin',def:'Farbstoff in der Basalzellschicht — schützt vor UV-Strahlung'},
  {term:'Melanozyten',def:'Melanin-produzierende Zellen in der Basalzellschicht der Epidermis'},
  {term:'Säureschutzmantel',def:'Hydro-Lipid-Film aus Talg (Talgdrüsen) + Schweiß (Schweißdrüsen) — schützt vor Keimen'},
  {term:'Residente Hautflora',def:'Dauerhaft auf der Haut vorhandene, nicht pathogene Mikroorganismen'},
  {term:'Transiente Hautflora',def:'Vorübergehend auf der Haut vorhandene, nicht pathogene Mikroorganismen'},
  {term:'Leistenhaut',def:'Haut an Handflächen und Fußsohlen — mit Leisten/Furchen, bis 9mm dick'},
  {term:'Felderhaut',def:'Haut am restlichen Körper — größter Teil, Gesäß 3mm, Gesicht <1mm'},
  {term:'Basalzellschicht',def:'Unterste Epidermisschicht — enthält Stammzellen und Melanozyten, auf Basalmembran'},
  {term:'Diffusion',def:'Passiver Transport von höherer zu niedrigerer Konzentration — versorgt die Epidermis'},
  {term:'Malignes Melanom',def:'Hautkrebs ausgehend von Melanozyten — sehr bösartig, metastasiert lymphogen + hämatogen'},
  {term:'Papillenschicht',def:'1. Schicht der Dermis — viele Blutgefäße, Druck kann diese komprimieren → Dekubitus!'},
  {term:'Geflechtschicht',def:'2. Schicht der Dermis — kollagenreiche elastische Fasern, Elastizität nimmt im Alter ab'},
  {term:'Glanzzellschicht',def:'Nur in Leistenhaut! Direkt unter Hornschicht, bricht UV-Licht stark (UV-Schutz)'},
  {term:'Stachelzellschicht',def:'Epidermisschicht mit stachelförmigen Zellen — verleiht der Haut besondere Festigkeit'},
  {term:'Körnerzellschicht',def:'Enthält Keratohyalinkörner (Eiweißkörper) — langsame Verhornung der Zellen'},
  {term:'Hornzellschicht',def:'Äußerste Epidermisschicht — abgestorbene kernlose Zellen, Dicke je nach Belastung'},
  {term:'Haarpapille',def:'Basis des Haares — Zellen teilen sich hier, Blutgefäße versorgen das Wachstum'},
  {term:'Haarfollikel',def:'Haarbalg — Einstülpung der Epidermis die das Haar umgibt, enthält Talgdrüse'},
  {term:'M. erector pili',def:'Haaraufrichtungsmuskel — kontrahiert bei Kälte/Angst → Gänsehaut'},
  {term:'Paronychie',def:'Entzündung von Nagelfalz und Nagelwall — durch Bakterien, bei Eiter → Panaritium'},
  {term:'Panaritium',def:'Schwere eitrige Entzündung am Finger/Nagel — Komplikation einer Paronychie'},
  {term:'Seborrhoische Haut',def:'Fettige Haut (50% der Bevölkerung) — grobporig, Pickel, Überproduktion der Talgdrüsen'},
  {term:'Sebostatische Haut',def:'Trockene Haut (30% der Bevölkerung) — spröde, rissig, schuppig, verminderte Talgproduktion'},
  {term:'Fitzpatrick-Skala',def:'Klassifikation der 6 Hauttypen nach UV-Empfindlichkeit — von keltisch (Typ 1) bis schwarz (Typ 6)'},
  {term:'Altershaut',def:'Kapillaren ↓, Epidermiserneuerung langsamer, Subcutis↓ → pergamentartig, trocken, Falten, Pigmentflecken'},
  {term:'Vater-Pacini-Körperchen',def:'Mechanorezeptor in der Subcutis — reagiert auf Vibration'},
  {term:'Meissner-Tastkörperchen',def:'Mechanorezeptor in der Dermis — reagiert auf Berührung/Tasten'},
  {term:'Merkel-Tastzellen',def:'Mechanorezeptor in der Oberhaut (Basalzellschicht) — reagiert auf Druck'},
  // Dekubitus
  {term:'Dekubitus',def:'Lokal begrenzte Schädigung der Haut/Gewebe über knöchernen Vorsprüngen durch Druck oder Druck+Scherkräfte (NPUAP/EPUAP)'},
  {term:'Ischämie',def:'Minderdurchblutung → Nährstoffmangel (Hypoxie) + Anreicherung Stoffwechselprodukte → Zelluntergang'},
  {term:'Scherkräfte',def:'Entgegengesetzt zueinander wirkende Kräfte innerhalb eines Gewebes — wichtiger Entstehungsfaktor des Dekubitus'},
  {term:'EPUAP',def:'European Pressure Ulcer Advisory Panel — europäische Fachgesellschaft für Dekubituseinstufung (Kategorie I–IV)'},
  {term:'NPUAP',def:'National Pressure Ulcer Advisory Panel — amerikanische Fachgesellschaft, gemeinsam mit EPUAP für Klassifikation zuständig'},
  {term:'Prädilektionsstellen',def:'Bevorzugte Stellen der Dekubitusentstehung: Kreuzbein, Steißbein, Fersen, Trochanter, Schulterblätter'},
  {term:'IAD',def:'Inkontinenz-assoziierte Dermatitis — Hautschaden durch Kontakt mit Urin/Stuhl. Kein Dekubitus! (Ausschlussdiagnose)'},
  {term:'Intertrigo (ITD)',def:'Intertriginöse Dermatitis — Hautschaden in Körperfalten durch Schwitzen/Reibung. In der Rima ani, inguinal.'},
  {term:'Dekubitus Kategorie I',def:'Nicht wegdrückbare Rötung bei intakter Haut über knöchernem Vorsprung — kann schmerzhaft, verhärtet, warm/kalt sein'},
  {term:'Dekubitus Kategorie II',def:'Teilzerstörung der Haut bis zur Dermis — flache Wunde oder Blase, ohne Beläge/Nekrose/Bluterguss'},
  {term:'Dekubitus Kategorie III',def:'Zerstörung aller Hautschichten, kein freiliegender Knochen/Muskel/Sehne — Tunnel möglich'},
  {term:'Dekubitus Kategorie IV',def:'Totaler Gewebsverlust mit freiliegendem Knochen, Sehnen oder Muskeln — Osteomyelitis möglich'},
  {term:'Expertenstandard DNQP',def:'Deutsches Netzwerk für Qualitätsentwicklung in der Pflege — 6 Handlungsebenen zur Dekubitusprophylaxe (2017)'},
  {term:'Braden-Skala',def:'Risikoskala zur Dekubituseinschätzung — CAVE: kein Beweis für Senkung der Inzidenz, nur unterstützend'},
  {term:'MASD',def:'Moisture-associated skin damage — Feuchtigkeitsbedingte Hautschäden (IAD, Intertrigo, Mazeration)'},
  {term:'NPWT',def:'Negative Pressure Wound Therapy — Unterdrucktherapie zur Wundheilung bei tiefen Dekubitus (z.B. CuraSul®)'},
];
